# Generated by Django 4.2.1 on 2023-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('filling', models.CharField(max_length=100, verbose_name='Начинка')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена')),
                ('category', models.CharField(choices=[('candy-bar', 'candy-bar'), ('cake', 'cake'), ('pastry', 'pastry')], default='cake', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(default='default.jpg', upload_to='cakes/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
