# Generated by Django 4.2.1 on 2023-06-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cake', 'cake'), ('pastry', 'pastry'), ('candy-bar', 'candy-bar')], default='cake', max_length=20, verbose_name='Категория'),
        ),
    ]
